import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{Users,Settings2,Save,Plus,X,Download,Sparkles,GripVertical,MapPin,ChevronDown,ChevronRight,Pencil,Trash2}from'lucide-react';
import'./styles.css';
const API='/api',DEFAULT_ROLES=['MD','RN','MA','Sonographer','FOS'],DEFAULT_LANES=['Admin','Off','Remote','Hospital','Vacation'];
const COLORS={MD:'#f8d676',RN:'#fda4af',MA:'#86efac',Sonographer:'#c4b5fd',FOS:'#7dd3fc'};
const deep=x=>JSON.parse(JSON.stringify(x));
const fallback={version:2.1,date:'2026-10-12',period:'Full Day',roles:DEFAULT_ROLES,sites:['Kennesaw','Smyrna','Douglasville','Avalon','LaGrange','Paulding','Woodstock','Griffin/Sunday'],closedSites:[],clinicTypes:{'Standard Cardiology':{mode:'In-person',requirements:{MD:1,RN:0,MA:1,Sonographer:1,FOS:1}},'Double Provider':{mode:'In-person',requirements:{MD:2,RN:1,MA:3,Sonographer:2,FOS:1}},'Fetal Clinic':{mode:'In-person',requirements:{MD:1,RN:0,MA:0,Sonographer:1,FOS:0}},'Hybrid Echo':{mode:'Hybrid',requirements:{MD:1,RN:0,MA:0,Sonographer:1,FOS:1}},Telemedicine:{mode:'Telemedicine',requirements:{MD:1,RN:0,MA:0,Sonographer:0,FOS:0}},'Remote Echo':{mode:'Remote diagnostics',requirements:{MD:0,RN:0,MA:0,Sonographer:1,FOS:1}}},siteClinics:{Kennesaw:'Standard Cardiology',Smyrna:'Standard Cardiology',Douglasville:'Standard Cardiology',Avalon:'Standard Cardiology',LaGrange:'Hybrid Echo',Paulding:'Standard Cardiology',Woodstock:'Standard Cardiology','Griffin/Sunday':'Standard Cardiology'},staff:[['Dr. Sacks','MD'],['Dr. Makadia','MD'],['Dr. Yaari','MD'],['Raven','RN'],['Marshall','RN'],['Micah','MA'],['Kyonna','MA'],['Whittney','MA'],['Kim','Sonographer'],['Brittany','Sonographer'],['Mallory','Sonographer'],['Delaine','Sonographer'],['Dannille','FOS'],['Heather','FOS'],['Nicole','FOS'],['Samantha','FOS'],['Jackie','FOS']],assignments:{Kennesaw:{MD:['Dr. Sacks'],RN:[],MA:['Micah'],Sonographer:['Kim'],FOS:['Dannille','Heather']},Smyrna:{MD:['Dr. Makadia'],RN:[],MA:['Kyonna'],Sonographer:['Brittany'],FOS:['Nicole']},Douglasville:{MD:['Dr. Yaari'],RN:['Raven'],MA:['Whittney'],Sonographer:['Mallory'],FOS:['Samantha']}},lanes:{Admin:['Jackie'],Off:[],Remote:[],Hospital:['Delaine'],Vacation:[]},overrides:{daily:{},weekly:{}},audit:[]};
function weekStart(v){const d=new Date(v+'T12:00:00');d.setDate(d.getDate()-((d.getDay()+6)%7));return d.toISOString().slice(0,10)}
function normalize(raw){const d={...deep(fallback),...deep(raw||{})};d.roles=d.roles||DEFAULT_ROLES;d.closedSites=d.closedSites||[];d.lanes={...deep(fallback.lanes),...(d.lanes||{})};d.overrides={daily:{},weekly:{},...(d.overrides||{})};d.assignments=d.assignments||{};d.sites.forEach(s=>{d.siteClinics[s]??='Standard Cardiology';d.assignments[s]??={};d.roles.forEach(r=>d.assignments[s][r]??=[])});return d}
function App(){
 const[state,setState]=useState(null),[view,setView]=useState('All Roles'),[tab,setTab]=useState('Board'),[toast,setToast]=useState(''),[prompt,setPrompt]=useState(''),[reply,setReply]=useState('Ask about a location, staffing gap, or requirement.'),[rosterOpen,setRosterOpen]=useState(false),[clinicOpen,setClinicOpen]=useState(false),[locationOpen,setLocationOpen]=useState(false),[collapsedOpen,setCollapsedOpen]=useState(false);
 useEffect(()=>{fetch(API+'/state').then(r=>r.ok?r.json():Promise.reject()).then(x=>setState(normalize(x))).catch(()=>setState(normalize(fallback)))},[]);
 if(!state)return <div className="loading">Loading Workforce Operations Center…</div>;
 const shown=view==='All Roles'?state.roles:[view],activeSites=state.sites.filter(s=>!state.closedSites.includes(s)),closedSites=state.sites.filter(s=>state.closedSites.includes(s));
 const notify=t=>{setToast(t);setTimeout(()=>setToast(''),1800)};
 const update=fn=>setState(prev=>{const d=deep(prev);fn(d);return normalize(d)});
 const effective=site=>{const type=state.siteClinics[site],base={...(state.clinicTypes[type]?.requirements||{})},w=state.overrides.weekly[weekStart(state.date)+'|'+site],day=state.overrides.daily[state.date+'|'+site];return{type,source:day?'Daily':w?'Weekly':'Baseline',requirements:{...base,...w,...day}}};
 const occupied=new Set([...state.sites.flatMap(s=>state.roles.flatMap(r=>state.assignments[s]?.[r]||[])),...Object.values(state.lanes).flat()]);
 function removeEverywhere(name,d){d.sites.forEach(s=>d.roles.forEach(r=>d.assignments[s][r]=d.assignments[s][r].filter(n=>n!==name)));Object.keys(d.lanes).forEach(l=>d.lanes[l]=d.lanes[l].filter(n=>n!==name))}
 function assign(name,site,role){const p=state.staff.find(x=>x[0]===name&&x[1]===role);if(!p)return notify(`Choose a ${role} from the roster`);update(d=>{removeEverywhere(name,d);d.assignments[site][role].push(name);d.audit.unshift({at:new Date().toISOString(),action:`Assigned ${name} to ${site} as ${role}`})});notify(`Assigned ${name}`)}
 function moveLane(name,lane){update(d=>{removeEverywhere(name,d);d.lanes[lane].push(name);d.audit.unshift({at:new Date().toISOString(),action:`Moved ${name} to ${lane}`})})}
 function remove(name){update(d=>removeEverywhere(name,d))}
 function setClinic(site,type){update(d=>{d.siteClinics[site]=type;d.audit.unshift({at:new Date().toISOString(),action:`Changed ${site} clinic to ${type}`})})}
 function closeSite(site){update(d=>{if(!d.closedSites.includes(site))d.closedSites.push(site);d.audit.unshift({at:new Date().toISOString(),action:`Closed ${site} for ${d.date}`})});notify(`${site} collapsed`)}
 function reopenSite(site){update(d=>d.closedSites=d.closedSites.filter(x=>x!==site))}
 async function save(){try{const r=await fetch(API+'/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});if(!r.ok)throw Error();notify('Saved')}catch{localStorage.setItem('woc-v2',JSON.stringify(state));notify('Saved in browser')}}
 function generate(){let count=0;update(d=>{activeSites.forEach(site=>{const req=effective(site).requirements;d.roles.forEach(role=>{while(d.assignments[site][role].length<(req[role]||0)){const busy=new Set([...d.sites.flatMap(s=>d.assignments[s][role]),...Object.values(d.lanes).flat()]);const p=d.staff.find(x=>x[1]===role&&!busy.has(x[0]));if(!p)break;d.assignments[site][role].push(p[0]);count++}})});d.audit.unshift({at:new Date().toISOString(),action:`Generated ${count} draft assignments`})});notify(`${count} draft assignment(s)`)}
 function ask(){const q=prompt.toLowerCase(),site=state.sites.find(s=>q.includes(s.toLowerCase())),role=state.roles.find(r=>q.includes(r.toLowerCase()));if(!site||!role)return setReply('Mention both a location and a role, for example: “Why does Kennesaw need one sonographer?”');const e=effective(site),names=state.assignments[site][role],need=e.requirements[role]||0;setReply(`${site} · ${role}\nClinic: ${e.type}\nSource: ${e.source}\nRequired: ${need}\nAssigned: ${names.join(', ')||'None'}\nMissing: ${Math.max(0,need-names.length)}`)}
 function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`workforce-${state.date}.json`;a.click()}
 return <div><header><div><h1>Workforce Operations Center</h1><p>Daily huddle staffing board</p></div><div className="headerActions"><button onClick={()=>setLocationOpen(true)}><MapPin/>Locations</button><button onClick={()=>setRosterOpen(true)}><Users/>Roster</button><button onClick={()=>setClinicOpen(true)}><Settings2/>Baselines</button><button className="primary" onClick={save}><Save/>Save</button></div></header>
 <nav>{['Board','Audit'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>
 {tab==='Board'&&<><section className="toolbar"><label>Date<input type="date" value={state.date} onChange={e=>setState({...state,date:e.target.value})}/></label><label>Period<select value={state.period} onChange={e=>setState({...state,period:e.target.value})}><option>Full Day</option><option>AM</option><option>PM</option></select></label><label>View<select value={view} onChange={e=>setView(e.target.value)}><option>All Roles</option>{state.roles.map(r=><option key={r}>{r}</option>)}</select></label><button className="coverage" onClick={generate}><Sparkles/>Generate Draft Coverage</button><button onClick={exportData}><Download/>Export</button></section>
 <div className="layout"><main><div className="legend"><span className="covered">Covered</span><span className="shortage">Missing</span><span className="excess">Extra</span><span className="none">Not needed</span></div><div className="tableWrap"><table><thead><tr><th>Location / Clinic</th>{shown.map(r=><th key={r}>{r}</th>)}</tr></thead><tbody>{activeSites.map(site=><tr key={site}><td className="site"><div className="siteTop"><strong>{site}</strong><button title="Close and collapse" onClick={()=>closeSite(site)}><X/></button></div><select value={state.siteClinics[site]} onChange={e=>setClinic(site,e.target.value)}>{Object.keys(state.clinicTypes).map(t=><option key={t}>{t}</option>)}</select></td>{shown.map(role=><BoardCell key={role} site={site} role={role} state={state} details={effective(site)} assign={assign} remove={remove}/>)}</tr>)}</tbody></table></div>
 {closedSites.length>0&&<div className="closedSites"><button onClick={()=>setCollapsedOpen(!collapsedOpen)}>{collapsedOpen?<ChevronDown/>:<ChevronRight/>}{closedSites.length} closed location(s)</button>{collapsedOpen&&<div>{closedSites.map(s=><button className="reopen" key={s} onClick={()=>reopenSite(s)}>{s} · Reopen</button>)}</div>}</div>}<Lanes state={state} moveLane={moveLane}/></main>
 <aside><section className="assistant"><h2><Sparkles/>Staffing Assistant</h2><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Why does Kennesaw need one sonographer?"/><button className="primary" onClick={ask}>Ask</button><pre>{reply}</pre></section><section><h2>Unassigned Staff</h2>{state.staff.filter(x=>(view==='All Roles'||x[1]===view)&&!occupied.has(x[0])).map(x=><StaffPill key={x[0]} name={x[0]} role={x[1]}/>)}</section></aside></div></>}
 {tab==='Audit'&&<div className="page"><h2>Audit</h2>{state.audit.map((a,i)=><div className="audit" key={i}><b>{a.action}</b><span>{a.at}</span></div>)}</div>}
 {rosterOpen&&<RosterModal state={state} update={update} close={()=>setRosterOpen(false)} notify={notify}/>} {clinicOpen&&<ClinicModal state={state} update={update} close={()=>setClinicOpen(false)} notify={notify}/>} {locationOpen&&<LocationModal state={state} update={update} close={()=>setLocationOpen(false)} notify={notify}/>} {toast&&<div className="toast">{toast}</div>}</div>
}
function BoardCell({site,role,state,details,assign,remove}){const[typed,setTyped]=useState(''),need=details.requirements[role]||0,names=state.assignments[site][role],status=need===0&&!names.length?'none':names.length<need?'shortage':names.length>need?'excess':'covered';return <td className={`cell ${status}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const x=JSON.parse(e.dataTransfer.getData('application/json'));assign(x.name,site,role)}}>{names.map(n=><StaffPill key={n} name={n} role={role} onRemove={()=>remove(n)}/>)}<div className="compactStatus" title={`${details.source}: required ${need}, assigned ${names.length}`}><b>{names.length}/{need}</b><span>{names.length<need?`−${need-names.length} missing`:names.length>need?`+${names.length-need} extra`:details.source}</span></div><div className="assignBox"><input list={`pick-${site}-${role}`} value={typed} onChange={e=>setTyped(e.target.value)} placeholder={`Add ${role}`}/><datalist id={`pick-${site}-${role}`}>{state.staff.filter(x=>x[1]===role).map(x=><option key={x[0]} value={x[0]}/>)}</datalist><button onClick={()=>{assign(typed,site,role);setTyped('')}}><Plus/></button></div></td>}
function StaffPill({name,role,onRemove}){return <div className="pill" draggable onDragStart={e=>e.dataTransfer.setData('application/json',JSON.stringify({name,role}))} style={{'--role':COLORS[role]||'#cbd5e1'}}><GripVertical/><span>{name}</span><small>{role}</small>{onRemove&&<button onClick={onRemove}><X/></button>}</div>}
function Lanes({state,moveLane}){return <div className="lanes">{Object.keys(state.lanes).map(l=><div className="lane" key={l}><strong>{l}</strong><div onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const x=JSON.parse(e.dataTransfer.getData('application/json'));moveLane(x.name,l)}}>{state.lanes[l].map(n=><StaffPill key={n} name={n} role={state.staff.find(x=>x[0]===n)?.[1]||''}/>)}</div></div>)}</div>}
function Modal({title,children,close}){return <div className="modalBack"><div className="modal"><button className="close" onClick={close}><X/></button><h2>{title}</h2>{children}</div></div>}
function RosterModal({state,update,close,notify}){const[name,setName]=useState(''),[role,setRole]=useState(state.roles[0]),[editing,setEditing]=useState(null),sorted=[...state.staff].sort((a,b)=>a[1].localeCompare(b[1])||a[0].localeCompare(b[0]));function savePerson(){if(!name.trim())return;update(d=>{if(editing){const old=editing[0];d.staff=d.staff.map(x=>x[0]===old?[name.trim(),role]:x);d.sites.forEach(s=>d.roles.forEach(r=>d.assignments[s][r]=d.assignments[s][r].map(n=>n===old?name.trim():n)));Object.keys(d.lanes).forEach(l=>d.lanes[l]=d.lanes[l].map(n=>n===old?name.trim():n))}else d.staff.push([name.trim(),role])});setName('');setEditing(null);notify(editing?'Roster updated':'Staff added')}function edit(p){setEditing(p);setName(p[0]);setRole(p[1])}function del(p){update(d=>{d.staff=d.staff.filter(x=>x[0]!==p[0]);d.sites.forEach(s=>d.roles.forEach(r=>d.assignments[s][r]=d.assignments[s][r].filter(n=>n!==p[0])));Object.keys(d.lanes).forEach(l=>d.lanes[l]=d.lanes[l].filter(n=>n!==p[0]))});notify('Removed from roster')}return <Modal title="Editable Roster" close={close}><div className="rosterTable">{sorted.map(p=><div className="rosterRow" key={p[0]}><span className="roleTag" style={{background:COLORS[p[1]]||'#e2e8f0'}}>{p[1]}</span><b>{p[0]}</b><button onClick={()=>edit(p)}><Pencil/></button><button className="danger" onClick={()=>del(p)}><Trash2/></button></div>)}</div><h3>{editing?'Edit staff member':'Add staff member'}</h3><div className="formGrid"><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}>{state.roles.map(r=><option key={r}>{r}</option>)}</select></label></div><button className="primary" onClick={savePerson}>{editing?'Save Changes':'Add Staff'}</button>{editing&&<button onClick={()=>{setEditing(null);setName('')}}>Cancel</button>}</Modal>}
function ClinicModal({state,update,close,notify}){const[editing,setEditing]=useState(null),[name,setName]=useState(''),[mode,setMode]=useState('In-person'),[req,setReq]=useState(Object.fromEntries(state.roles.map(r=>[r,0])));function edit(n,v){setEditing(n);setName(n);setMode(v.mode);setReq({...v.requirements})}function saveType(){if(!name.trim())return;update(d=>{if(editing&&editing!==name){d.clinicTypes[name]={mode,requirements:req};delete d.clinicTypes[editing];Object.keys(d.siteClinics).forEach(s=>{if(d.siteClinics[s]===editing)d.siteClinics[s]=name})}else d.clinicTypes[name]={mode,requirements:req}});setEditing(null);setName('');setReq(Object.fromEntries(state.roles.map(r=>[r,0])));notify('Baseline saved')}return <Modal title="Clinic Types & Baselines" close={close}><div className="baselineGrid">{Object.entries(state.clinicTypes).map(([n,v])=><button className="baselineCard" key={n} onClick={()=>edit(n,v)}><b>{n}</b><small>{v.mode}</small><span>{state.roles.map(r=>`${r} ${v.requirements[r]||0}`).join(' · ')}</span></button>)}</div><h3>{editing?'Edit Baseline':'Add Clinic Type'}</h3><div className="formGrid"><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Mode<select value={mode} onChange={e=>setMode(e.target.value)}>{['In-person','Hybrid','Telemedicine','Remote diagnostics','Administrative'].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="roleReqs">{state.roles.map(r=><label key={r}>{r}<input type="number" min="0" value={req[r]||0} onChange={e=>setReq({...req,[r]:+e.target.value})}/></label>)}</div><button className="primary" onClick={saveType}>{editing?'Save Baseline':'Add Clinic Type'}</button></Modal>}
function LocationModal({state,update,close,notify}){const[name,setName]=useState('');function add(){if(!name.trim())return;update(d=>{d.sites.push(name.trim());d.siteClinics[name.trim()]=Object.keys(d.clinicTypes)[0];d.assignments[name.trim()]={};d.roles.forEach(r=>d.assignments[name.trim()][r]=[])});setName('');notify('Location added')}return <Modal title="Locations" close={close}><div className="locationList">{state.sites.map(s=><div key={s}><b>{s}</b><span>{state.closedSites.includes(s)?'Closed':'Open'}</span></div>)}</div><h3>Add Location</h3><div className="formGrid"><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label></div><button className="primary" onClick={add}>Add Location</button></Modal>}
createRoot(document.getElementById('root')).render(<App/>);
