import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{CalendarDays,Users,Building2,Sparkles,Save,Plus,X,Settings2,Download,RotateCcw,ChevronDown,AlertTriangle,CheckCircle2,GripVertical}from'lucide-react';
import'./styles.css';
const API='/api';
const ROLES=['MD','RN','MA','Sonographer','FOS'];
const LANES=['Admin','Off','Remote','Hospital'];
const COLORS={MD:'#f8d676',RN:'#fda4af',MA:'#86efac',Sonographer:'#c4b5fd',FOS:'#7dd3fc'};
const fallback={date:'2026-10-12',period:'Full Day',sites:['Kennesaw','Smyrna','Douglasville','Avalon','LaGrange','Paulding','Woodstock','Griffin/Sunday'],clinicTypes:{'Standard Cardiology':{mode:'In-person',requirements:{MD:1,RN:0,MA:1,Sonographer:1,FOS:1}},'Double Provider':{mode:'In-person',requirements:{MD:2,RN:1,MA:3,Sonographer:2,FOS:1}},'Fetal Clinic':{mode:'In-person',requirements:{MD:1,RN:0,MA:0,Sonographer:1,FOS:0}},'Hybrid Echo':{mode:'Hybrid',requirements:{MD:1,RN:0,MA:0,Sonographer:1,FOS:1}},Telemedicine:{mode:'Telemedicine',requirements:{MD:1,RN:0,MA:0,Sonographer:0,FOS:0}},'Remote Echo':{mode:'Remote diagnostics',requirements:{MD:0,RN:0,MA:0,Sonographer:1,FOS:1}}},siteClinics:{Kennesaw:'Standard Cardiology',Smyrna:'Standard Cardiology',Douglasville:'Standard Cardiology',Avalon:'Standard Cardiology',LaGrange:'Hybrid Echo',Paulding:'Standard Cardiology',Woodstock:'Standard Cardiology','Griffin/Sunday':'Standard Cardiology'},staff:[['Dr. Sacks','MD'],['Dr. Makadia','MD'],['Dr. Yaari','MD'],['Raven','RN'],['Micah','MA'],['Kyonna','MA'],['Whittney','MA'],['Kim','Sonographer'],['Brittany','Sonographer'],['Mallory','Sonographer'],['Dannille','FOS'],['Heather','FOS'],['Nicole','FOS'],['Samantha','FOS'],['Jackie','FOS'],['Delaine','Sonographer'],['Marshall','MD']],assignments:{Kennesaw:{MD:['Dr. Sacks'],RN:[],MA:['Micah'],Sonographer:['Kim'],FOS:['Dannille','Heather']},Smyrna:{MD:['Dr. Makadia'],RN:[],MA:['Kyonna'],Sonographer:['Brittany'],FOS:['Nicole']},Douglasville:{MD:['Dr. Yaari'],RN:['Raven'],MA:['Whittney'],Sonographer:['Mallory'],FOS:['Samantha']}},lanes:{Admin:['Jackie','Heather','Delaine'],Off:[],Remote:['Marshall'],Hospital:['Delaine']},overrides:{daily:{},weekly:{}},audit:[]};
const deep=x=>JSON.parse(JSON.stringify(x));
function weekStart(value){const d=new Date(value+'T12:00:00');d.setDate(d.getDate()-((d.getDay()+6)%7));return d.toISOString().slice(0,10)}
function App(){
 const[state,setState]=useState(null),[view,setView]=useState('All Roles'),[selected,setSelected]=useState(null),[tab,setTab]=useState('Board'),[toast,setToast]=useState(''),[prompt,setPrompt]=useState(''),[reply,setReply]=useState('Ask about coverage, requirements, vacations, or a location.'),[clinicOpen,setClinicOpen]=useState(false),[rosterOpen,setRosterOpen]=useState(false);
 useEffect(()=>{fetch(API+'/state').then(r=>r.ok?r.json():Promise.reject()).then(setState).catch(()=>setState(deep(fallback)))},[]);
 const notify=t=>{setToast(t);setTimeout(()=>setToast(''),1800)};
 if(!state)return <div className="loading">Loading Workforce Operations Center…</div>;
 const ensureSite=s=>{state.assignments[s]??={};ROLES.forEach(r=>state.assignments[s][r]??=[])};state.sites.forEach(ensureSite);
 const shown=view==='All Roles'?ROLES:[view];
 function effective(site){const type=state.siteClinics[site],base={...(state.clinicTypes[type]?.requirements||{})},w=state.overrides.weekly[weekStart(state.date)+'|'+site],d=state.overrides.daily[state.date+'|'+site];return{type,source:d?'Daily override':w?'Weekly override':'Baseline',requirements:{...base,...w,...d}}}
 const occupied=useMemo(()=>new Set([...state.sites.flatMap(s=>ROLES.flatMap(r=>state.assignments[s]?.[r]||[])),...Object.values(state.lanes).flat()]),[state]);
 function removeEverywhere(name,draft){draft.sites.forEach(s=>ROLES.forEach(r=>draft.assignments[s][r]=draft.assignments[s][r].filter(n=>n!==name)));Object.keys(draft.lanes).forEach(l=>draft.lanes[l]=draft.lanes[l].filter(n=>n!==name))}
 function assign(name,site,role){const person=state.staff.find(x=>x[0]===name);if(!person||person[1]!==role)return notify(`Choose a ${role} from the roster`);setState(prev=>{const d=deep(prev);removeEverywhere(name,d);d.assignments[site][role].push(name);d.audit.unshift({at:new Date().toISOString(),action:`Assigned ${name} to ${site} as ${role}`});return d});notify(`Assigned ${name}`)}
 function move(name,site,role){assign(name,site,role)}
 function laneMove(name,lane){setState(prev=>{const d=deep(prev);removeEverywhere(name,d);d.lanes[lane].push(name);d.audit.unshift({at:new Date().toISOString(),action:`Moved ${name} to ${lane}`});return d});notify(`Moved ${name} to ${lane}`)}
 function remove(name){setState(prev=>{const d=deep(prev);removeEverywhere(name,d);return d})}
 async function save(){try{const r=await fetch(API+'/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});if(!r.ok)throw 0;notify('Saved')}catch{localStorage.setItem('workforce-state',JSON.stringify(state));notify('Saved in browser')}}
 function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`workforce-${state.date}.json`;a.click()}
 function generate(){let changes=[];setState(prev=>{const d=deep(prev);d.sites.forEach(site=>{const req=effective(site).requirements;ROLES.forEach(role=>{while(d.assignments[site][role].length<(req[role]||0)){const busy=new Set([...d.sites.flatMap(s=>d.assignments[s][role]),...Object.values(d.lanes).flat()]);const p=d.staff.find(x=>x[1]===role&&!busy.has(x[0]));if(!p)break;d.assignments[site][role].push(p[0]);changes.push(`${p[0]} → ${site} (${role})`)}})});d.audit.unshift({at:new Date().toISOString(),action:`Generated ${changes.length} draft assignments`});return d});setReply(changes.length?`Draft coverage generated:\n${changes.map(x=>'• '+x).join('\n')}\n\nReview before saving.`:'No qualified unassigned staff were available for remaining gaps.');notify(`${changes.length} draft assignments`)}
 function ask(){const q=prompt.toLowerCase();const site=state.sites.find(s=>q.includes(s.toLowerCase()))||selected?.site;const role=ROLES.find(r=>q.includes(r.toLowerCase()))||selected?.role;if(site&&role){const e=effective(site),names=state.assignments[site][role],need=e.requirements[role]||0;setReply(`${site} · ${role}\nClinic: ${e.type}\nRequirement source: ${e.source}\nRequired: ${need}\nAssigned: ${names.join(', ')||'None'}\nMissing: ${Math.max(0,need-names.length)}\n\nThe requirement is explicit and editable at the baseline, weekly, or daily level.`)}else setReply('Mention a location and role, or click a staffing cell first. Example: “Why does Kennesaw need one sonographer?”')}
 return <div className="app"><header><div><h1>Workforce Operations Center</h1><p>Daily huddle board, scheduling, clinic templates, coverage, and transparent staffing logic</p></div><div className="headerActions"><button onClick={()=>setRosterOpen(true)}><Users/>Roster</button><button onClick={()=>setClinicOpen(true)}><Settings2/>Clinic Types</button><button className="primary" onClick={save}><Save/>Save</button></div></header>
 <nav>{['Board','Weekly Overview','Audit'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav>
 {tab==='Board'&&<><section className="toolbar"><label>Date<input type="date" value={state.date} onChange={e=>setState({...state,date:e.target.value})}/></label><label>Period<select value={state.period} onChange={e=>setState({...state,period:e.target.value})}><option>Full Day</option><option>AM</option><option>PM</option></select></label><label>View<select value={view} onChange={e=>setView(e.target.value)}><option>All Roles</option>{ROLES.map(x=><option key={x}>{x}</option>)}</select></label><button className="coverage" onClick={generate}><Sparkles/>Generate Draft Coverage</button><button onClick={exportData}><Download/>Export</button></section>
 <div className="content"><main><div className="legend"><span className="lg covered">Covered</span><span className="lg shortage">Missing</span><span className="lg excess">Extra</span><span className="lg none">Not needed</span></div><div className="tableWrap"><table><thead><tr><th>Staff Scheduling</th>{shown.map(r=><th key={r}>{r}</th>)}</tr></thead><tbody>{state.sites.map(site=><tr key={site}><td className="site"><strong>{site}</strong><small>{state.siteClinics[site]}</small></td>{shown.map(role=><BoardCell key={role} site={site} role={role} state={state} effective={effective} onAssign={assign} onMove={move} onRemove={remove} onSelect={()=>setSelected({site,role})}/>)}</tr>)}</tbody></table></div><Lanes state={state} onDrop={laneMove}/></main><aside><section className="assistant"><h2><Sparkles/>Staffing Assistant</h2><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Why does Kennesaw need one sonographer? Cover today's absences."/><button className="primary" onClick={ask}>Ask</button><pre>{reply}</pre></section><section><h2>Unassigned Staff</h2><p className="muted">Drag to a cell, or use a cell's searchable name box.</p>{state.staff.filter(x=>(view==='All Roles'||x[1]===view)&&!occupied.has(x[0])).map(x=><StaffPill key={x[0]} name={x[0]} role={x[1]}/>)}</section>{selected&&<CellEditor selected={selected} state={state} setState={setState} effective={effective} notify={notify}/>}</aside></div></>}
 {tab==='Weekly Overview'&&<Weekly state={state}/>} {tab==='Audit'&&<Audit state={state}/>} {clinicOpen&&<ClinicModal state={state} setState={setState} close={()=>setClinicOpen(false)} notify={notify}/>} {rosterOpen&&<RosterModal state={state} setState={setState} close={()=>setRosterOpen(false)} notify={notify}/>} {toast&&<div className="toast" role="status">{toast}</div>}</div>
}
function StaffPill({name,role,onRemove}){return <div className="pill" draggable onDragStart={e=>e.dataTransfer.setData('application/json',JSON.stringify({name,role}))} style={{'--role':COLORS[role]}}><GripVertical/><span>{name}</span><small>{role}</small>{onRemove&&<button onClick={onRemove} aria-label={`Remove ${name}`}><X/></button>}</div>}
function BoardCell({site,role,state,effective,onAssign,onMove,onRemove,onSelect}){const e=effective(site),need=e.requirements[role]||0,names=state.assignments[site][role],status=need===0&&!names.length?'none':names.length<need?'shortage':names.length>need?'excess':'covered';const[typed,setTyped]=useState('');return <td className={`cell ${status}`} onClick={onSelect} onDragOver={e=>e.preventDefault()} onDrop={ev=>{ev.preventDefault();const x=JSON.parse(ev.dataTransfer.getData('application/json'));onMove(x.name,site,role)}}>{names.map(n=><StaffPill key={n} name={n} role={role} onRemove={()=>onRemove(n)}/>)}<div className="cellStatus"><b>Required {need}</b> · Assigned {names.length} · Missing {Math.max(0,need-names.length)}<br/><span>{e.source}</span></div><div className="assignBox"><input list={`list-${site}-${role}`} value={typed} onChange={x=>setTyped(x.target.value)} onClick={x=>x.stopPropagation()} placeholder={`Type or choose ${role}`}/><datalist id={`list-${site}-${role}`}>{state.staff.filter(x=>x[1]===role).map(x=><option key={x[0]} value={x[0]}/>)}</datalist><button onClick={x=>{x.stopPropagation();onAssign(typed,site,role);setTyped('')}}><Plus/></button></div></td>}
function Lanes({state,onDrop}){return <div className="lanes">{LANES.map(l=><div className="lane" key={l}><strong>{l}</strong><div onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const x=JSON.parse(e.dataTransfer.getData('application/json'));onDrop(x.name,l)}}>{state.lanes[l].map(n=>{const role=state.staff.find(x=>x[0]===n)?.[1]||'';return <StaffPill key={n} name={n} role={role}/>})}<span className="dropHint">Drop staff here</span></div></div>)}</div>}
function CellEditor({selected,state,setState,effective,notify}){const e=effective(selected.site);function apply(scope,role,value){setState(prev=>{const d=deep(prev);if(scope==='baseline')d.clinicTypes[e.type].requirements[role]=+value;else{const k=(scope==='daily'?d.date:weekStart(d.date))+'|'+selected.site;d.overrides[scope][k]={...(d.overrides[scope][k]||{}),[role]:+value}}return d});notify('Requirement updated')}return <section className="selected"><h2>{selected.site} · {selected.role}</h2><p><b>Clinic:</b> {e.type}<br/><b>Source:</b> {e.source}<br/><b>Assigned:</b> {state.assignments[selected.site][selected.role].join(', ')||'None'}</p><RequirementEditor current={e.requirements[selected.role]||0} role={selected.role} onApply={apply}/></section>}
function RequirementEditor({current,role,onApply}){const[v,setV]=useState(current),[scope,setScope]=useState('daily');return <div className="reqEditor"><label>Required {role}<input type="number" min="0" value={v} onChange={e=>setV(e.target.value)}/></label><label>Apply to<select value={scope} onChange={e=>setScope(e.target.value)}><option value="daily">Selected day</option><option value="weekly">Selected week</option><option value="baseline">Permanent baseline</option></select></label><button onClick={()=>onApply(scope,role,v)}>Apply</button></div>}
function Modal({title,children,close}){return <div className="modalBack"><div className="modal"><button className="close" onClick={close}><X/></button><h2>{title}</h2>{children}</div></div>}
function ClinicModal({state,setState,close,notify}){const[name,setName]=useState(''),[mode,setMode]=useState('In-person'),[req,setReq]=useState(Object.fromEntries(ROLES.map(r=>[r,0])));function add(){if(!name.trim())return;setState(p=>({...p,clinicTypes:{...p.clinicTypes,[name]:{mode,requirements:req}}}));notify('Clinic type added');setName('')}return <Modal title="Clinic Types & Baselines" close={close}><p className="muted">Add unlimited in-person, hybrid, telemedicine, remote diagnostic, outreach, or specialty clinic types.</p><div className="typeGrid">{Object.entries(state.clinicTypes).map(([n,v])=><div className="typeCard" key={n}><b>{n}</b><small>{v.mode}</small><p>{ROLES.map(r=>`${r} ${v.requirements[r]||0}`).join(' · ')}</p></div>)}</div><h3>Add clinic type</h3><div className="formGrid"><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Acworth Hybrid Echo"/></label><label>Mode<select value={mode} onChange={e=>setMode(e.target.value)}>{['In-person','Hybrid','Telemedicine','Remote diagnostics','Administrative'].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="roleReqs">{ROLES.map(r=><label key={r}>{r}<input type="number" min="0" value={req[r]} onChange={e=>setReq({...req,[r]:+e.target.value})}/></label>)}</div><button className="primary" onClick={add}>Add Clinic Type</button></Modal>}
function RosterModal({state,setState,close,notify}){const[name,setName]=useState(''),[role,setRole]=useState('MD');function add(){if(!name.trim())return;setState(p=>({...p,staff:[...p.staff,[name,role]]}));notify('Staff member added');setName('')}return <Modal title="Staff Roster" close={close}><div className="rosterList">{state.staff.map(x=><StaffPill key={x[0]} name={x[0]} role={x[1]}/>)}</div><h3>Add staff member</h3><div className="formGrid"><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}>{ROLES.map(x=><option key={x}>{x}</option>)}</select></label></div><button className="primary" onClick={add}>Add to Roster</button></Modal>}
function Weekly({state}){return <div className="page"><h2><CalendarDays/>Week of {weekStart(state.date)}</h2><p className="muted">Daily huddle summaries use the saved baseline plus weekly and daily overrides.</p><div className="weekCards">{['Monday','Tuesday','Wednesday','Thursday','Friday'].map(d=><div className="weekCard" key={d}><b>{d}</b><span>{state.sites.filter(s=>Object.values(state.assignments[s]||{}).flat().length).length} active locations</span></div>)}</div></div>}
function Audit({state}){return <div className="page"><h2>Audit & Accountability</h2>{state.audit.length?state.audit.map((a,i)=><div className="audit" key={i}><b>{a.action}</b><span>{a.at}</span></div>):<p>No changes recorded yet.</p>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
